# This file was generated by GoReleaser. DO NOT EDIT.
cask "eol-date" do
  name "eol-date"
  desc "CLI tool to check end-of-life dates for software products using the endoflife.date API."
  homepage "https://github.com/oliverandrich/eol-date"
  version "0.3.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eol-date"

  on_macos do
    on_intel do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-darwin-amd64.zip"
      sha256 "2548f058c6913c3005eceab2a2332c62f7fb6a178731aed2da3c174532086a2b"
    end
    on_arm do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-darwin-arm64.zip"
      sha256 "2a2c9ca467db5a962514206639bc3d17fd65a54793c8c2e7f89d5f2635a9581d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-linux-amd64.tar.gz"
      sha256 "3f1c448c67bc5081cdaa4278cb7b2869046544763119051a752ba3bad32b9d04"
    end
    on_arm do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-linux-arm64.tar.gz"
      sha256 "0f3cc527bda2583320e6cbc95ad0837b30503bc7da4d64abb68a1c323dd0768c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eol-date"]
    end
  end

  # No zap stanza required
end
