# This file was generated by GoReleaser. DO NOT EDIT.
cask "eol-date" do
  name "eol-date"
  desc "CLI tool to check end-of-life dates for software products using the endoflife.date API."
  homepage "https://github.com/oliverandrich/eol-date"
  version "0.1.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eol-date"

  on_macos do
    on_intel do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-darwin-amd64.zip"
      sha256 "22bc49440afffc999c0b941cdd6fb716f3daef93be911931a9df26130716826e"
    end
    on_arm do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-darwin-arm64.zip"
      sha256 "dc16ad5144cfbace5e2531044dd726a94b25f62d57115f85743ca0cfa39301d3"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-linux-amd64.tar.gz"
      sha256 "35a0466bafe20cc363c3e64adcd795061f2934a3cb671a44afc35427f1ad2816"
    end
    on_arm do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-linux-arm64.tar.gz"
      sha256 "db6d9ccc107e7afc3449d805a7e4be700533b327bb82194ad214220ae2766e3c"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eol-date"]
    end
  end

  # No zap stanza required
end
