# This file was generated by GoReleaser. DO NOT EDIT.
cask "eol-date" do
  name "eol-date"
  desc "CLI tool to check end-of-life dates for software products using the endoflife.date API."
  homepage "https://github.com/oliverandrich/eol-date"
  version "0.2.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "eol-date"

  on_macos do
    on_intel do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-darwin-amd64.zip"
      sha256 "df1490a851ff0ad14bac792bc2f891056e794796ffa26cf127d723c6ff3675b9"
    end
    on_arm do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-darwin-arm64.zip"
      sha256 "40da2d3205172ae4caa0fad5d0fad7d218968e5056427029f607d8fd1b774260"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-linux-amd64.tar.gz"
      sha256 "e4e85b003d6bd72ec18e8a8ec83af7048ed2569182d132c6ca8d86b0ab67818a"
    end
    on_arm do
      url "https://github.com/oliverandrich/eol-date/releases/download/v#{version}/eol-date-#{version}-linux-arm64.tar.gz"
      sha256 "cf7395435f7896a356ec8a3fc83f4e33bec1442747bf61ec34f1739fff05f375"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/eol-date"]
    end
  end

  # No zap stanza required
end
