# This file was generated by GoReleaser. DO NOT EDIT.
cask "gohatch" do
  name "gohatch"
  desc "A project scaffolding tool for Go"
  homepage "https://github.com/oliverandrich/gohatch"
  version "0.4.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gohatch"

  on_macos do
    on_intel do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-darwin-amd64.zip"
      sha256 "6c36b26516f7de7697eb721f36b567dc25a5f2b3e56306e2b24d51e543948bad"
    end
    on_arm do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-darwin-arm64.zip"
      sha256 "50f7fa2c78e01a6ee63b49535955e18ba1d0e26fcb362e3d8453505ab0c4694a"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-linux-amd64.tar.gz"
      sha256 "8fffbda81cdb9a427979766a48548c2e61634369feb3849b39a29e45845ba87d"
    end
    on_arm do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-linux-arm64.tar.gz"
      sha256 "390e0ca28b2803714035be4c65697d64c9da735bb8ed206e079b7941e83f8b5b"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gohatch"]
    end
  end

  # No zap stanza required
end
