# This file was generated by GoReleaser. DO NOT EDIT.
cask "gohatch" do
  name "gohatch"
  desc "A project scaffolding tool for Go"
  homepage "https://github.com/oliverandrich/gohatch"
  version "0.7.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gohatch"

  on_macos do
    on_intel do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-darwin-amd64.zip"
      sha256 "8aeb6a1f8c4e67adefb0891382996e665c04e0f571bec842b26a2a8e5cc78916"
    end
    on_arm do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-darwin-arm64.zip"
      sha256 "7bef4abfdda88dea4c7733355ee991d77e25c7e8f2e2e2890fb6c363a7f9370e"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-linux-amd64.tar.gz"
      sha256 "08a9c44d1b9869fcf913b02c0c3c9b137627b643014016a4b1a770e24f2f6e4e"
    end
    on_arm do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-linux-arm64.tar.gz"
      sha256 "3b65bf12ffb5c9b09dd80b061ad8cb5f8e93eecfa0ee23e328e604370697d5fe"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gohatch"]
    end
  end

  # No zap stanza required
end
