# This file was generated by GoReleaser. DO NOT EDIT.
cask "gohatch" do
  name "gohatch"
  desc "A project scaffolding tool for Go"
  homepage "https://github.com/oliverandrich/gohatch"
  version "0.7.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gohatch"

  on_macos do
    on_intel do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-darwin-amd64.zip"
      sha256 "6cae704ace9385862becdffe54f10f13873a526bd3d6b0b16da1dd3409dffe5f"
    end
    on_arm do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-darwin-arm64.zip"
      sha256 "9618c070974f01a87b56bca3131254fd80416475ca58f9786561ef8ce5cc2a95"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-linux-amd64.tar.gz"
      sha256 "6e0f9d3a69b5740ac7f3ab1573805f079c22d28cd44afce09bb0498e672a9e42"
    end
    on_arm do
      url "https://github.com/oliverandrich/gohatch/releases/download/v#{version}/gohatch-#{version}-linux-arm64.tar.gz"
      sha256 "9c95ae4278d61bacd112be95cba39d7c26af5640d6d7aecde908fc6f593d8509"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gohatch"]
    end
  end

  # No zap stanza required
end
